### ISSUE TITLE
Support for higher bit rates

### ISSUE THREAD

**Issue by best4username** [glv2/gmsk-transfer#1]
Hello
What we need to support higher bit rates ( firstly in receiver side ) ?
The max bit rate I cloud reach ( I7 8th cpu ) is  700000 at reeciver side, because it use just one core , I have done a C profiling on the code to see the bottle nick 
![asd](https://user-images.githubusercontent.com/53115443/123641699-30de4b00-d82b-11eb-8363-274a05ac80be.png)
a small digging in liquid-dsp docs I have found [ this article ](https://liquidsdr.org/blog/raspberry-pi3-benchmarks/) and wish it can help :
[benchmark_threaded.txt](https://github.com/glv2/gmsk-transfer/files/6726494/benchmark_threaded.txt)

also it is good to add  run examples for real hardware test (commands and images ) .

**Comment by glv2** [comment]
I think we can't do much in gmsk-transfer to get higher bit rates because the bottleneck is inside the liquid-dsp library.
We would need liquid-dsp to have faster dot product functions (optimized assembly routines or multi-threading).

**Comment by glv2** [comment]
Using a smaller value for the maximum allowable carrier deviation (with the '-u' option) should reduce the amount of work that the frame detector has to do, and therefore increase the maximum bit rate a little.
But this will only work if the clocks of the radios are precise enough, otherwise the frames might not get detected at all.
